s
mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: cn.eeka.sharedservices.wechat.entity
  mapper-locations:
    - classpath:/mappers/**/*.xml
security:
  basic:
    enabled: true
  sessions: always
  user:
    name: micro
    password: micro
    role:
      - USER
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://10.7.121.117:3306/wechat_coupon?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: eekao2o
    filters: stat,wall,log4j     #druid监控配置
    dbcp2:
      min-idle: 5         #数据库连接池的最小维持连接数
      initial-size: 5     #初始化提供的连接数
      max-total: 5          #最大的连接数
      max-wait-millis: 200        #等待连接获取的最大超时时间