server:
  port: 9292
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: shared-services-zuul
spring:
  application:
    name: shared-services-zuul
zuul:
  ignored-services: "*"
  routes:
    shared-services-wechat-coupon-api-without-security:
      path: /wechat-coupon-without-security/**
      serviceId: shared-services-wechat-coupon-api-without-security
    shared-services-wechat-coupon-api:
      path: /wechat-coupon/**
      serviceId: shared-services-wechat-coupon-api
