feign:
  compression:
    request:
      mime-types:
        - text/xml
        - application/xml
        - application/json
      min-request-size: 2048
server:
  port: 80
spring:
  eureka:
    client:
      service-url:
        default-zone: http://localhost:8761/eureka